Corrigindo: "Não existe planilhas"
dadosjusbr/parser-mpms pull request #3
Opened 2022-07-13 19:50 UTC by Joellensilva

2022-07-17 21:32 UTC, danielfireman commented on src/data.py
> +    if(int(year) == 2018 or int(year) == 2019 and int(month)<=6):
Não está muito claro o objetivo dessa mudança.

2022-07-17 21:33 UTC, danielfireman requested changes

2022-07-17 21:33 UTC, danielfireman commented on src/parser.py
> +            remuneracao.valor = abs(remuneracao.valor)
Os testes de unidade passaram?

2022-07-20 23:45 UTC, Joellensilva commented
Sobre a correção dos testes de unidade: eu expliquei melhor sobre os erros que encontrei no Slack. E sim, agora os testes de unidade passaram!

2022-07-26 16:48 UTC, danielfireman approved these changes

2022-07-26 16:54 UTC, merged